# Generated by Django 5.0.6 on 2024-06-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCampeonato', models.CharField(max_length=30, verbose_name='Nombre de campeonato')),
                ('nombreAuspiciante', models.CharField(max_length=30, verbose_name='Nombre de auspiciante')),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(verbose_name='Año del campeonato')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscampeonatosxequipo', to='futbolec.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre de equipo')),
                ('siglas', models.CharField(max_length=5, verbose_name='Siglas del equipo')),
                ('twitter', models.CharField(max_length=30, unique=True, verbose_name='Usuario de Twitter')),
                ('campeonatos', models.ManyToManyField(through='futbolec.CampeonatoEquipo', to='futbolec.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='campeonatoequipo',
            name='equipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loscampeonatosxequipo', to='futbolec.equipo'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='futbolec.CampeonatoEquipo', to='futbolec.equipo'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre del jugador')),
                ('posicionCampo', models.CharField(max_length=30, verbose_name='Posición del jugador')),
                ('numeroCamiseta', models.IntegerField(verbose_name='Número de camiseta')),
                ('sueldo', models.FloatField(verbose_name='Sueldo del jugador')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbolec.equipo')),
            ],
        ),
    ]
